"""create_orders_invoices_payments_tables_and_update_products

Revision ID: 08b67abab6c8
Revises: 520ea1bca1ef
Create Date: 2026-09-19 12:50:10.332105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08b67abab6c8'
down_revision: Union[str, Sequence[str], None] = '520ea1bca1ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('unit', sa.String(length=10), nullable=False))
    op.add_column('order_items', sa.Column('discount_pct', sa.Numeric(precision=5, scale=2), nullable=False))
    op.add_column('order_items', sa.Column('discount_amt', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('order_items', sa.Column('hsn_code', sa.String(length=10), nullable=False))
    op.add_column('order_items', sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=False))
    op.add_column('order_items', sa.Column('gst_amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('order_items', sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False))
    op.alter_column('order_items', 'quantity',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=3),
               existing_nullable=False)
    op.alter_column('order_items', 'subtotal',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.add_column('orders', sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('orders', sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('orders', sa.Column('gst_amount', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('orders', sa.Column('remarks', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('delivery_date', sa.Date(), nullable=True))
    op.add_column('orders', sa.Column('approved_by_id', sa.Integer(), nullable=True))
    op.alter_column('orders', 'total_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.create_foreign_key(None, 'orders', 'users', ['approved_by_id'], ['id'])
    op.add_column('products', sa.Column('dealer_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('products', sa.Column('pcs_per_carton', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'pcs_per_carton')
    op.drop_column('products', 'dealer_price')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.alter_column('orders', 'total_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_column('orders', 'approved_by_id')
    op.drop_column('orders', 'delivery_date')
    op.drop_column('orders', 'remarks')
    op.drop_column('orders', 'gst_amount')
    op.drop_column('orders', 'discount_amount')
    op.drop_column('orders', 'subtotal')
    op.alter_column('order_items', 'subtotal',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('order_items', 'quantity',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('order_items', 'total')
    op.drop_column('order_items', 'gst_amount')
    op.drop_column('order_items', 'gst_rate')
    op.drop_column('order_items', 'hsn_code')
    op.drop_column('order_items', 'discount_amt')
    op.drop_column('order_items', 'discount_pct')
    op.drop_column('order_items', 'unit')
    # ### end Alembic commands ###
